package com.m36.mediaserver.domain

import com.m36.mediaserver.ssdp.SsdpServer

/** Immutable, UI-safe snapshot of the server's live state. */
data class ServerDiagnostics(
    val running: Boolean = false,
    val serverStatus: String = "Stopped",
    val currentNetwork: String = "Not connected",
    val activeInterface: String = "—",
    val activeServerIpv4: String = "—",
    val activeTransport: String = "None",
    val defaultTransport: String = "Unknown",
    val ipv4Addresses: List<String> = emptyList(),
    val httpBindAddress: String = "—",
    val httpPort: Int = 8200,
    val ssdpStatus: String = "Stopped",
    val ssdpInterface: String = "—",
    val multicastAddress: String = "${SsdpServer.GROUP_ADDRESS}:${SsdpServer.PORT}",
    val multicastSocketCreated: Boolean = false,
    val multicastGroupJoined: Boolean = false,
    val multicastDetails: String = "—",
    val mSearchCount: Long = 0,
    val lastSsdpRequest: String = "—",
    val ssdpResponsesSent: Long = 0,
    val httpRequestCount: Long = 0,
    val lastHttpRequest: String = "—",
    val lastMediaHttpExchange: String = "—",
    val mediaHttpHistory: List<String> = emptyList(),
    val rootDescriptionGetCount: Long = 0,
    val lastRootDescriptionGet: String = "—",
    val contentDirectoryScpdGetCount: Long = 0,
    val lastContentDirectoryScpdGet: String = "—",
    val contentDirectoryControlRequestCount: Long = 0,
    val lastContentDirectoryControlRequest: String = "—",
    val lastContentDirectoryControlHttpStatus: String = "—",
    val lastContentDirectorySoapAction: String = "—",
    val lastContentDirectorySoapContentType: String = "—",
    val lastContentDirectorySoapBody: String = "—",
    val lastContentDirectorySoapActionName: String = "—",
    val lastContentDirectorySoapActionNamespace: String = "—",
    val lastContentDirectorySoapRecognition: String = "—",
    val contentDirectorySoapHistory: List<String> = emptyList(),
    val advertisedContentDirectoryServiceType: String = "—",
    val advertisedContentDirectoryServiceId: String = "—",
    val advertisedContentDirectoryScpdUrl: String = "—",
    val advertisedContentDirectoryControlUrl: String = "—",
    val advertisedContentDirectoryEventSubUrl: String = "—",
    val lastContentDirectoryBrowseRequest: String = "—",
    val lastContentDirectoryBrowseResult: String = "—",
    val lastSafEnumeration: String = "—",
    val selectedFolder: String = "Not selected",
)
